# Generated by Django 3.1 on 2020-09-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GazSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vat', models.IntegerField(default=23)),
                ('conversion_rate', models.FloatField(default=11.506)),
                ('distribution_fee', models.DecimalField(decimal_places=5, default=0.04937, max_digits=1000)),
                ('gaz_fuel', models.DecimalField(decimal_places=5, default=0.08944, max_digits=1000)),
                ('subscription_fee', models.DecimalField(decimal_places=2, default=6.38, max_digits=1000)),
                ('distribution_fee_constant', models.DecimalField(decimal_places=2, default=3.49, max_digits=1000)),
            ],
        ),
    ]
