# Generated by Django 3.1 on 2020-09-01 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GazCounterUnitPriceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=1.3, max_digits=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GazCounterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('monthly_usage', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit_price', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gaz_counter.gazcounterunitpricemodel')),
            ],
        ),
    ]
