# Generated by Django 3.1 on 2020-09-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaz_counter', '0002_auto_20200901_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gazcountermodel',
            name='total_cost',
        ),
    ]
