# Generated by Django 3.1 on 2020-09-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powercountermodel',
            name='monthly_usage',
            field=models.IntegerField(default=0),
        ),
    ]
